# Generated by Django 5.0.3 on 2024-04-10 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AREA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EMPRESA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=20)),
                ('registro_patronal', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PREGUNTAS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EMPLEADO',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('calle', models.CharField(max_length=100)),
                ('numero_casa', models.CharField(max_length=20)),
                ('colonia', models.CharField(max_length=100)),
                ('cp', models.IntegerField()),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=20)),
                ('nss', models.CharField(max_length=20)),
                ('rfc', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('dias_vacaciones', models.IntegerField()),
                ('puesto', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='lider_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_empleado', to='core.empleado'),
        ),
        migrations.CreateModel(
            name='NOMINA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('salario_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percepciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deducciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='NOTICIAS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='PERMISO',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Personal', 'Personal'), ('Medico', 'Medico'), ('Emergencia', 'Emergencia'), ('Incapacidad', 'Incapacidad')], max_length=20)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='REPORTE',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Enviado', 'Enviado'), ('En revision', 'En revision'), ('Corregido', 'Corregido')], max_length=20)),
                ('seccion', models.CharField(blank=True, choices=[('Login', 'Inicio de Sesion'), ('Permisos', 'Permisos'), ('Vacaciones', 'Vacaciones'), ('Nomina', 'Nomina'), ('Noticias', 'Noticias'), ('Preguntas', 'Preguntas'), ('Datos personales', 'Datos personales'), ('Otro', 'Otro')], max_length=20, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='VACACIONES',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ESTADO_SOLICITUD',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('En revision', 'En revision'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('comentarios_admin', models.TextField(blank=True, null=True)),
                ('id_permiso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.permiso')),
                ('id_vacaciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vacaciones')),
            ],
        ),
    ]
