# Generated by Django 5.0.3 on 2024-04-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado_solicitud',
            options={'verbose_name_plural': 'Estado de solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='vacaciones',
            options={'verbose_name_plural': 'Vacaciones'},
        ),
        migrations.AlterModelTable(
            name='noticias',
            table='NOTICIA',
        ),
        migrations.AlterModelTable(
            name='preguntas',
            table='PREGUNTA',
        ),
    ]
