# Generated by Django 5.0.3 on 2024-04-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_estado_solicitud_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticias',
            options={'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='preguntas',
            options={'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelTable(
            name='noticias',
            table='core_noticia',
        ),
        migrations.AlterModelTable(
            name='preguntas',
            table='core_pregunta',
        ),
    ]
