# Generated by Django 5.0.3 on 2024-04-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_noticias_options_alter_preguntas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
