# Generated by Django 5.0.3 on 2024-04-10 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_area_lider_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_solicitud',
            name='id_permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.permiso'),
        ),
        migrations.AlterField(
            model_name='estado_solicitud',
            name='id_vacaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vacaciones'),
        ),
    ]
