# Generated by Django 5.0.2 on 2024-04-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empleado_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='fecha_publicacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='fecha_solicitud',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_solicitud',
            field=models.DateField(auto_now=True),
        ),
    ]
