# Generated by Django 5.0.2 on 2024-04-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_area_id_alter_empleado_id_alter_empresa_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacaciones',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
