# Generated by Django 5.0.2 on 2024-05-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vacaciones_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
