# Generated by Django 5.0.4 on 2024-05-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_noticias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas'),
        ),
    ]
