# Generated by Django 5.0.4 on 2024-05-05 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_permiso_cancelado'),
        ('core', '0013_alter_preguntas_imagen'),
    ]

    operations = [
    ]
