# Generated by Django 5.0.3 on 2024-05-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_empleado_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
